language: node_js

node_js:
  - 8
cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm run start &

script:
  - npm build
  - npm test

deploy:
  provider: heroku
  app: webpack4-react16
  api_key: $HEROKU_KEY
