language: node_js

node_js:
  - 8

cache:
  directories:
    -"node_modules"

install:
  - npm install

script:
  - npm build

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: webpack4-react16
